
// This file is automatically generated. Do not modify it manually.

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
export const firebaseConfig = {
  apiKey: "YOUR_API_KEY",
  m authDomain: "pichulik-studios.firebaseapp.com",
  projectId: "pichulik-studios",
  storageBucket: "pichulik-studios.appspot.com",
  messagingSenderId: "656553941649",
  appId: "1:656553941649:web:06b833219484a141d43139",
  measurementId: "G-L5G7EB30R4",
};

if (!firebaseConfig.apiKey || firebaseConfig.apiKey === "YOUR_API_KEY") {
  throw new Error(
    "Firebase API key is not configured. Please add it to your environment variables."
  );
}
